spring:
  profiles:
    active: dev
  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB



logging:
  level:
    org:
      springframework:
        web: INFO

mybatis:
  typeAliasesPackage: com.bin.webmonitor.repository.domain
  mapperLocations: classpath:mappers/**.xml
